# Generated by Django 5.1.3 on 2024-11-19 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('hours_worked', models.PositiveIntegerField(verbose_name='Часы работы')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж (лет)')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('start_city', models.CharField(max_length=255, verbose_name='Город отправления')),
                ('end_city', models.CharField(max_length=255, verbose_name='Город прибытия')),
                ('date', models.DateField(verbose_name='Дата')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='s.employee', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='Efficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efficiency_value', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Коэффициент эффективности')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency', to='s.schedule', verbose_name='Расписание')),
            ],
        ),
    ]
